{% set name = "juliart" %}
{% set version = "0.0.16" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a9c071ed9a8b65aeff80adabe1c61884b025af126a9997b7dacfd4f96dd10de

build:
  number: 4
  entry_points:
    - juliart=juliart.client:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: True  # [win or py2k]
  
requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - Pillow >=6.0.0
    - imageio >=2.5.0

test:
  imports:
    - juliart
    - juliart.colors
    - juliart.client
    - juliart.main
    - juliart.namer
    - juliart.utils
    - juliart.version
  commands:
    - juliart --help

about:
  home: https://www.github.com/vsoch/juliart
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: Command line tool for generating Julia Set images and animations
  doc_url: https://github.com/vsoch/juliart
  dev_url: https://github.com/vsoch/juliart

extra:
  recipe-maintainers:
    - vsoch
